### PR TITLE
Small contrib

### PR DESCRIPTION
**Pull request by xakraz**
* Pagination support in `api.get_by_name`
* Error handling in the 1st request to Netbox to display info to the user
* Dockerfile for running

### CODE REVIEW

**Comment by bpetit** [comment]
Thank you for your contribution. Looks great. I'll take a deeper look this weekend.

**Review by bpetit — CHANGES_REQUESTED** [review]
Thanks again for contributing. I'm ok with everything, but could you remove the extra comma line 228 ? Because of that the show function returns a list of one dictionnary to the user instead of a single dictionnary.

**Comment by xakraz** [comment]
Yeah sure, this was a typo :)

**Comment by bpetit** [comment]
Thank you for the PR, it's all good.

**Comment by xakraz** [comment]
Happy to contribute !
In the following weeks I hope beeing able to add tests and CI :)

**Comment by bpetit** [comment]
I just added basic tests with Travis CI. But it surely could be improved (more integration tests, coverage tests, etc...)

Thanks again ! Are you using the library for a personal project ?

**Comment by xakraz** [comment]
I am mainly using the CLI at my company :)
Maybe we will have a fork under our organization if I convince other people of my team to use it.

**Pull request merged**
